name: CI
on: 
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Use your bucket region here
        
    # Here you could add some building steps if you were dealing with some angular/react/Vue...
    # - name: Build static site
    #  run: yarn install && npm run-script build
    
    - name: Deploy static site to S3 bucket
      run: aws s3 cp ./moodyssources3/ s3://moodysdestination --recursive
    - name: Create CF Template
      run: aws glue create-job --name sapmoodystest --role arn:aws:iam::222045979822:role/Test_NIH_New --command "Name=glueetl,ScriptLocation=s3://moodyssources3/samplecode.py",PythonVersion=3 --max-retries=2 --timeout=3600
      #run: aws ecr create-repository --repository-name testmoodyspipeline
      # --delete flag will remove any file in the s3 that are not on the "thefoldertodeploy" folder
